# Generated by Django 5.2.8 on 2026-05-08 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_comentario', models.TextField(verbose_name='Seu comentário sobre o Capi Busque')),
                ('ajudou_preparacao', models.CharField(choices=[('S', 'Sim, ajudou bastante'), ('P', 'Ajudou parcialmente'), ('N', 'Ainda não, mas estou explorando')], default='S', max_length=1, verbose_name='O site te ajudou na preparação/decisão para o ENEM?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo (Visível para o público)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
