# Generated by Django 5.2.8 on 2026-05-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='ajudou_preparacao',
            field=models.CharField(choices=[('S', 'Sim'), ('P', 'Parcialmente'), ('N', 'Ainda não')], default='S', max_length=1, verbose_name='O site te ajudou na preparação/decisão para o ENEM?'),
        ),
    ]
