# Generated by Django 5.2.8 on 2026-04-30 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=50)),
                ('year_reference', models.IntegerField()),
                ('course_name', models.CharField(max_length=200)),
                ('campus', models.CharField(max_length=100)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('shift', models.CharField(max_length=50)),
                ('total_spots_filled', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuotaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('spots', models.IntegerField(default=0)),
                ('previous_cutoff', models.FloatField(blank=True, null=True)),
                ('historical_max_score', models.FloatField(blank=True, null=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='cota_min_and_max_enem.courseoffering')),
            ],
        ),
    ]
