# Generated by Django 5.2.8 on 2026-04-30 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cota_min_and_max_enem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilCandidatoDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola_publica', models.BooleanField(default=True, verbose_name='Estudou em Escola Pública?')),
                ('renda_sm', models.FloatField(default=1.0, verbose_name='Renda Familiar (em Salários Mínimos)')),
                ('raca', models.CharField(choices=[('branca', 'Branca'), ('preta', 'Preta'), ('parda', 'Parda'), ('indigena', 'Indígena'), ('quilombola', 'Quilombola')], default='branca', max_length=20, verbose_name='Raça/Cor')),
                ('pcd', models.BooleanField(default=False, verbose_name='Pessoa com Deficiência (PCD)?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_candidato', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
