# Generated by Django 6.0.4 on 2026-05-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cota_min_and_max_enem', '0002_perfilcandidatodb'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='leftover_spots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perfilcandidatodb',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perfilcandidatodb',
            name='renda_sm',
            field=models.FloatField(default=1.0, verbose_name='Renda Familiar (em Salários Mínimos por pessoa na residência)'),
        ),
        migrations.AlterField(
            model_name='quotadata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
