# Generated by Django 5.2.8 on 2026-05-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cota_min_and_max_enem', '0003_courseoffering_leftover_spots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perfilcandidatodb',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quotadata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
