# Generated by Django 5.2.8 on 2026-07-01 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favoritos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorito',
        ),
    ]
